if (worldName != "pja305") exitWith {};

OPEX_mapRadius = worldSize / 2;
OPEX_mapCenter = [OPEX_mapRadius, OPEX_mapRadius, 0];
OPEX_mapRegion = "africa";
OPEX_mapCountry = "STR_nigeria";
OPEX_mapLocality = "STR_nziwasogo";
OPEX_mapLocalityInside = "STR_nziwasogoIn";
OPEX_mapClimate = "tropical";
OPEX_mapEnemy = "BOKO";
OPEX_mapNationalities = ["STR_nigeria", "STR_nigeria", "STR_nigeria", "STR_nigeria", "STR_nigeria", "STR_cameroon", "STR_somalia", "STR_kenya", "STR_sudan", "STR_mali"];
OPEX_mapLanguage = "englishFR";
OPEX_mapWater = true;
OPEX_locations_safe = [];
OPEX_locations_isolated = [];
OPEX_locations_villages = [];
OPEX_locations_cities = [];
OPEX_locations_industrial = [];
OPEX_locations_military = [];