waitUntil {!isNil "ALiVE_STATIC_DATA_LOADED"};
ALIVE_autoGeneratedTasks = ["MilAssault","MilDefence","CivAssault","Assassination", "DestroyVehicles","DestroyInfantry","SabotageBuilding","InsurgencyPatrol","InsurgencyDestroyAssets","Rescue","CSAR"];
